#!/usr/bin/env python3
"""Install a generated Hermes profile into ~/.hermes/profiles/<name>/.

Takes a profile generated by build_hermes_profile.py and installs it as a
runnable Hermes profile by:
1. Resolving template variables ({{...}}) with example/default values
2. Copying system-prompt.md → SOUL.md (Hermes's system prompt file)
3. Creating config.yaml with model + toolset settings
4. Copying persona skills into the profile's skills/ directory
5. Copying mcp-config.yaml for MCP tool integrations

Usage:
    python tools/install_hermes_profile.py [--profile construction-rfq] [--vars company_name="Acme Construction"]
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
HERMES_HOME = Path.home() / ".hermes"

# Default variable values for testing/demo
DEFAULT_VARS: dict[str, str] = {
    "company_name": "Acme Construction",
    "company_specialty": "general contractor",
    "markup_percentage": "15",
    "labor_rate": "85",
    "overhead_rate": "12",
    "response_time_target": "4 hours",
    "auto_send": "false",
    "escalation_threshold": "50000",
    "COMPANY_NAME": "Acme Construction",
}


def resolve_template_vars(text: str, variables: dict[str, str]) -> str:
    """Replace {{variable}} placeholders with values from the variables dict."""
    def replacer(match: re.Match) -> str:
        var_name = match.group(1).strip()
        return variables.get(var_name, match.group(0))

    return str(re.sub(r"\{\{(\w+)\}\}", replacer, text))


def install_profile(
    profile_slug: str,
    source_dir: Path | None = None,
    variables: dict[str, str] | None = None,
) -> Path:
    """Install a generated Hermes profile into ~/.hermes/profiles/.

    Args:
        profile_slug: Slug name of the profile (e.g. "construction-rfq").
        source_dir: Directory of the generated profile. Defaults to
                    hermes-profiles/<slug>/ in the repo root.
        variables: Template variable values. Defaults to DEFAULT_VARS.

    Returns:
        Path to the installed profile directory.
    """
    if source_dir is None:
        source_dir = REPO_ROOT / "hermes-profiles" / profile_slug
    if not source_dir.is_dir():
        raise FileNotFoundError(f"Profile source not found: {source_dir}")

    if variables is None:
        variables = DEFAULT_VARS

    target_dir = HERMES_HOME / "profiles" / profile_slug

    # Create the profile if it doesn't exist
    if not target_dir.is_dir():
        target_dir.mkdir(parents=True, exist_ok=True)
        print(f"✅ Created profile directory: {target_dir}")

    # 1. Install SOUL.md (system prompt)
    system_prompt_src = source_dir / "system-prompt.md"
    if system_prompt_src.is_file():
        content = resolve_template_vars(
            system_prompt_src.read_text(encoding="utf-8"), variables
        )
        soul_path = target_dir / "SOUL.md"
        soul_path.write_text(content, encoding="utf-8")
        print(f"   → SOUL.md (system prompt, {len(content)} bytes)")

    # 2. Install config.yaml
    config_src = source_dir / "config.yaml"
    if config_src.is_file():
        content = resolve_template_vars(
            config_src.read_text(encoding="utf-8"), variables
        )
        config_path = target_dir / "config.yaml"
        config_path.write_text(content, encoding="utf-8")
        print(f"   → config.yaml ({len(content)} bytes)")

    # 3. Install persona skills
    skills_src = source_dir / "skills"
    skills_target = target_dir / "skills"
    if skills_src.is_dir():
        for skill_dir in skills_src.iterdir():
            if skill_dir.is_dir():
                dest = skills_target / skill_dir.name
                if dest.exists():
                    shutil.rmtree(dest)
                shutil.copytree(skill_dir, dest)
                print(f"   → skills/{skill_dir.name}/")

    # 4. Install MCP config
    mcp_src = source_dir / "mcp-config.yaml"
    if mcp_src.is_file():
        content = resolve_template_vars(
            mcp_src.read_text(encoding="utf-8"), variables
        )
        mcp_path = target_dir / "mcp-config.yaml"
        mcp_path.write_text(content, encoding="utf-8")
        print(f"   → mcp-config.yaml ({len(content)} bytes)")

    # 5. Install onboarding config
    onboarding_src = source_dir / "onboarding.yaml"
    if onboarding_src.is_file():
        content = resolve_template_vars(
            onboarding_src.read_text(encoding="utf-8"), variables
        )
        onboarding_path = target_dir / "onboarding.yaml"
        onboarding_path.write_text(content, encoding="utf-8")
        print(f"   → onboarding.yaml ({len(content)} bytes)")

    # 6. Install cron jobs
    cron_src = source_dir / "cron"
    cron_target = target_dir / "cron"
    if cron_src.is_dir():
        cron_target.mkdir(parents=True, exist_ok=True)
        for cron_file in cron_src.iterdir():
            if cron_file.is_file():
                content = resolve_template_vars(
                    cron_file.read_text(encoding="utf-8"), variables
                )
                shutil.copy(
                    cron_file, cron_target / cron_file.name
                )
                print(f"   → cron/{cron_file.name}")

    print(f"\n🎉 Profile '{profile_slug}' installed to {target_dir}")
    print(f"   Test with: hermes -p {profile_slug} chat -q 'Hello'")
    return target_dir


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install a generated Hermes profile into ~/.hermes/profiles/."
    )
    parser.add_argument(
        "--profile",
        default="construction-rfq",
        help="Profile slug to install (default: construction-rfq)",
    )
    parser.add_argument(
        "--source",
        default=None,
        help="Source profile directory (default: hermes-profiles/<slug>/)",
    )
    parser.add_argument(
        "--vars",
        nargs="*",
        default=None,
        help="Template variables as key=value pairs",
    )
    args = parser.parse_args()

    variables = dict(DEFAULT_VARS)
    if args.vars:
        for pair in args.vars:
            key, _, value = pair.partition("=")
            variables[key] = value

    source = Path(args.source) if args.source else None
    install_profile(args.profile, source, variables)


if __name__ == "__main__":
    main()
